#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'onchip_memory2_1', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_1_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_1_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_1_COMPONENT_NAME onchip_memory2_1
#define ONCHIP_MEMORY2_1_BASE 0x0
#define ONCHIP_MEMORY2_1_SPAN 19200
#define ONCHIP_MEMORY2_1_END 0x4aff
#define ONCHIP_MEMORY2_1_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_1_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_1_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_1_DUAL_PORT 1
#define ONCHIP_MEMORY2_1_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_1_INIT_CONTENTS_FILE soc_system_onchip_memory2_1
#define ONCHIP_MEMORY2_1_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_1_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_1_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_1_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_1_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_1_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_1_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_1_SIZE_VALUE 19200
#define ONCHIP_MEMORY2_1_WRITABLE 1
#define ONCHIP_MEMORY2_1_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_1_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_1_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_1_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_1_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_1_MEMORY_INFO_MEM_INIT_DATA_WIDTH 8
#define ONCHIP_MEMORY2_1_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_1

/*
 * Macros for device 'pio_sw', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_SW_'.
 * The prefix is the slave descriptor.
 */
#define PIO_SW_COMPONENT_TYPE altera_avalon_pio
#define PIO_SW_COMPONENT_NAME pio_sw
#define PIO_SW_BASE 0x8000
#define PIO_SW_SPAN 16
#define PIO_SW_END 0x800f
#define PIO_SW_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_SW_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_SW_CAPTURE 0
#define PIO_SW_DATA_WIDTH 10
#define PIO_SW_DO_TEST_BENCH_WIRING 0
#define PIO_SW_DRIVEN_SIM_VALUE 0
#define PIO_SW_EDGE_TYPE NONE
#define PIO_SW_FREQ 50000000
#define PIO_SW_HAS_IN 1
#define PIO_SW_HAS_OUT 0
#define PIO_SW_HAS_TRI 0
#define PIO_SW_IRQ_TYPE NONE
#define PIO_SW_RESET_VALUE 0

/*
 * Macros for device 'pio_led', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_LED_'.
 * The prefix is the slave descriptor.
 */
#define PIO_LED_COMPONENT_TYPE altera_avalon_pio
#define PIO_LED_COMPONENT_NAME pio_led
#define PIO_LED_BASE 0x8010
#define PIO_LED_SPAN 16
#define PIO_LED_END 0x801f
#define PIO_LED_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LED_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LED_CAPTURE 0
#define PIO_LED_DATA_WIDTH 10
#define PIO_LED_DO_TEST_BENCH_WIRING 0
#define PIO_LED_DRIVEN_SIM_VALUE 0
#define PIO_LED_EDGE_TYPE NONE
#define PIO_LED_FREQ 50000000
#define PIO_LED_HAS_IN 0
#define PIO_LED_HAS_OUT 1
#define PIO_LED_HAS_TRI 0
#define PIO_LED_IRQ_TYPE NONE
#define PIO_LED_RESET_VALUE 1023

/*
 * Macros for device 'cursor_enable_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'CURSOR_ENABLE_PIO_'.
 * The prefix is the slave descriptor.
 */
#define CURSOR_ENABLE_PIO_COMPONENT_TYPE altera_avalon_pio
#define CURSOR_ENABLE_PIO_COMPONENT_NAME cursor_enable_pio
#define CURSOR_ENABLE_PIO_BASE 0x8020
#define CURSOR_ENABLE_PIO_SPAN 16
#define CURSOR_ENABLE_PIO_END 0x802f
#define CURSOR_ENABLE_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define CURSOR_ENABLE_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CURSOR_ENABLE_PIO_CAPTURE 0
#define CURSOR_ENABLE_PIO_DATA_WIDTH 32
#define CURSOR_ENABLE_PIO_DO_TEST_BENCH_WIRING 0
#define CURSOR_ENABLE_PIO_DRIVEN_SIM_VALUE 0
#define CURSOR_ENABLE_PIO_EDGE_TYPE NONE
#define CURSOR_ENABLE_PIO_FREQ 50000000
#define CURSOR_ENABLE_PIO_HAS_IN 0
#define CURSOR_ENABLE_PIO_HAS_OUT 1
#define CURSOR_ENABLE_PIO_HAS_TRI 0
#define CURSOR_ENABLE_PIO_IRQ_TYPE NONE
#define CURSOR_ENABLE_PIO_RESET_VALUE 0

/*
 * Macros for device 'cursor_x_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'CURSOR_X_PIO_'.
 * The prefix is the slave descriptor.
 */
#define CURSOR_X_PIO_COMPONENT_TYPE altera_avalon_pio
#define CURSOR_X_PIO_COMPONENT_NAME cursor_x_pio
#define CURSOR_X_PIO_BASE 0x8030
#define CURSOR_X_PIO_SPAN 16
#define CURSOR_X_PIO_END 0x803f
#define CURSOR_X_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define CURSOR_X_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CURSOR_X_PIO_CAPTURE 0
#define CURSOR_X_PIO_DATA_WIDTH 32
#define CURSOR_X_PIO_DO_TEST_BENCH_WIRING 0
#define CURSOR_X_PIO_DRIVEN_SIM_VALUE 0
#define CURSOR_X_PIO_EDGE_TYPE NONE
#define CURSOR_X_PIO_FREQ 50000000
#define CURSOR_X_PIO_HAS_IN 0
#define CURSOR_X_PIO_HAS_OUT 1
#define CURSOR_X_PIO_HAS_TRI 0
#define CURSOR_X_PIO_IRQ_TYPE NONE
#define CURSOR_X_PIO_RESET_VALUE 0

/*
 * Macros for device 'cursor_y_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'CURSOR_Y_PIO_'.
 * The prefix is the slave descriptor.
 */
#define CURSOR_Y_PIO_COMPONENT_TYPE altera_avalon_pio
#define CURSOR_Y_PIO_COMPONENT_NAME cursor_y_pio
#define CURSOR_Y_PIO_BASE 0x8040
#define CURSOR_Y_PIO_SPAN 16
#define CURSOR_Y_PIO_END 0x804f
#define CURSOR_Y_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define CURSOR_Y_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CURSOR_Y_PIO_CAPTURE 0
#define CURSOR_Y_PIO_DATA_WIDTH 32
#define CURSOR_Y_PIO_DO_TEST_BENCH_WIRING 0
#define CURSOR_Y_PIO_DRIVEN_SIM_VALUE 0
#define CURSOR_Y_PIO_EDGE_TYPE NONE
#define CURSOR_Y_PIO_FREQ 50000000
#define CURSOR_Y_PIO_HAS_IN 0
#define CURSOR_Y_PIO_HAS_OUT 1
#define CURSOR_Y_PIO_HAS_TRI 0
#define CURSOR_Y_PIO_IRQ_TYPE NONE
#define CURSOR_Y_PIO_RESET_VALUE 0

/*
 * Macros for device 'selection_enable_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'SELECTION_ENABLE_PIO_'.
 * The prefix is the slave descriptor.
 */
#define SELECTION_ENABLE_PIO_COMPONENT_TYPE altera_avalon_pio
#define SELECTION_ENABLE_PIO_COMPONENT_NAME selection_enable_pio
#define SELECTION_ENABLE_PIO_BASE 0x8050
#define SELECTION_ENABLE_PIO_SPAN 16
#define SELECTION_ENABLE_PIO_END 0x805f
#define SELECTION_ENABLE_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SELECTION_ENABLE_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SELECTION_ENABLE_PIO_CAPTURE 0
#define SELECTION_ENABLE_PIO_DATA_WIDTH 32
#define SELECTION_ENABLE_PIO_DO_TEST_BENCH_WIRING 0
#define SELECTION_ENABLE_PIO_DRIVEN_SIM_VALUE 0
#define SELECTION_ENABLE_PIO_EDGE_TYPE NONE
#define SELECTION_ENABLE_PIO_FREQ 50000000
#define SELECTION_ENABLE_PIO_HAS_IN 0
#define SELECTION_ENABLE_PIO_HAS_OUT 1
#define SELECTION_ENABLE_PIO_HAS_TRI 0
#define SELECTION_ENABLE_PIO_IRQ_TYPE NONE
#define SELECTION_ENABLE_PIO_RESET_VALUE 0

/*
 * Macros for device 'sel_x1_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'SEL_X1_PIO_'.
 * The prefix is the slave descriptor.
 */
#define SEL_X1_PIO_COMPONENT_TYPE altera_avalon_pio
#define SEL_X1_PIO_COMPONENT_NAME sel_x1_pio
#define SEL_X1_PIO_BASE 0x8060
#define SEL_X1_PIO_SPAN 16
#define SEL_X1_PIO_END 0x806f
#define SEL_X1_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SEL_X1_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEL_X1_PIO_CAPTURE 0
#define SEL_X1_PIO_DATA_WIDTH 32
#define SEL_X1_PIO_DO_TEST_BENCH_WIRING 0
#define SEL_X1_PIO_DRIVEN_SIM_VALUE 0
#define SEL_X1_PIO_EDGE_TYPE NONE
#define SEL_X1_PIO_FREQ 50000000
#define SEL_X1_PIO_HAS_IN 0
#define SEL_X1_PIO_HAS_OUT 1
#define SEL_X1_PIO_HAS_TRI 0
#define SEL_X1_PIO_IRQ_TYPE NONE
#define SEL_X1_PIO_RESET_VALUE 0

/*
 * Macros for device 'sel_y1_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'SEL_Y1_PIO_'.
 * The prefix is the slave descriptor.
 */
#define SEL_Y1_PIO_COMPONENT_TYPE altera_avalon_pio
#define SEL_Y1_PIO_COMPONENT_NAME sel_y1_pio
#define SEL_Y1_PIO_BASE 0x8070
#define SEL_Y1_PIO_SPAN 16
#define SEL_Y1_PIO_END 0x807f
#define SEL_Y1_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SEL_Y1_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEL_Y1_PIO_CAPTURE 0
#define SEL_Y1_PIO_DATA_WIDTH 32
#define SEL_Y1_PIO_DO_TEST_BENCH_WIRING 0
#define SEL_Y1_PIO_DRIVEN_SIM_VALUE 0
#define SEL_Y1_PIO_EDGE_TYPE NONE
#define SEL_Y1_PIO_FREQ 50000000
#define SEL_Y1_PIO_HAS_IN 0
#define SEL_Y1_PIO_HAS_OUT 1
#define SEL_Y1_PIO_HAS_TRI 0
#define SEL_Y1_PIO_IRQ_TYPE NONE
#define SEL_Y1_PIO_RESET_VALUE 0

/*
 * Macros for device 'sel_x2_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'SEL_X2_PIO_'.
 * The prefix is the slave descriptor.
 */
#define SEL_X2_PIO_COMPONENT_TYPE altera_avalon_pio
#define SEL_X2_PIO_COMPONENT_NAME sel_x2_pio
#define SEL_X2_PIO_BASE 0x8080
#define SEL_X2_PIO_SPAN 16
#define SEL_X2_PIO_END 0x808f
#define SEL_X2_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SEL_X2_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEL_X2_PIO_CAPTURE 0
#define SEL_X2_PIO_DATA_WIDTH 32
#define SEL_X2_PIO_DO_TEST_BENCH_WIRING 0
#define SEL_X2_PIO_DRIVEN_SIM_VALUE 0
#define SEL_X2_PIO_EDGE_TYPE NONE
#define SEL_X2_PIO_FREQ 50000000
#define SEL_X2_PIO_HAS_IN 0
#define SEL_X2_PIO_HAS_OUT 1
#define SEL_X2_PIO_HAS_TRI 0
#define SEL_X2_PIO_IRQ_TYPE NONE
#define SEL_X2_PIO_RESET_VALUE 0

/*
 * Macros for device 'sel_y2_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'SEL_Y2_PIO_'.
 * The prefix is the slave descriptor.
 */
#define SEL_Y2_PIO_COMPONENT_TYPE altera_avalon_pio
#define SEL_Y2_PIO_COMPONENT_NAME sel_y2_pio
#define SEL_Y2_PIO_BASE 0x8090
#define SEL_Y2_PIO_SPAN 16
#define SEL_Y2_PIO_END 0x809f
#define SEL_Y2_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define SEL_Y2_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define SEL_Y2_PIO_CAPTURE 0
#define SEL_Y2_PIO_DATA_WIDTH 32
#define SEL_Y2_PIO_DO_TEST_BENCH_WIRING 0
#define SEL_Y2_PIO_DRIVEN_SIM_VALUE 0
#define SEL_Y2_PIO_EDGE_TYPE NONE
#define SEL_Y2_PIO_FREQ 50000000
#define SEL_Y2_PIO_HAS_IN 0
#define SEL_Y2_PIO_HAS_OUT 1
#define SEL_Y2_PIO_HAS_TRI 0
#define SEL_Y2_PIO_IRQ_TYPE NONE
#define SEL_Y2_PIO_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1764593561

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
